<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria os livros, autores, assuntos e os relacionamentos.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE livro (
            cod_l INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            titulo VARCHAR(40) NOT NULL, 
            editora VARCHAR(40) NOT NULL, 
            edicao INT NOT NULL, 
            ano_publicacao VARCHAR(4) NOT NULL, 
            valor INT NOT NULL, 
            PRIMARY KEY(cod_l))');

        $this->addSql('CREATE TABLE autor (
            cod_au INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            nome VARCHAR(40) NOT NULL, 
            PRIMARY KEY(cod_au))');

        $this->addSql('CREATE TABLE assunto (
            cod_as INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            descricao VARCHAR(20) NOT NULL, 
            PRIMARY KEY(cod_as))');
        
        $this->addSql('CREATE TABLE livro_autor (
            livro_cod_l INT NOT NULL,
            autor_cod_au INT NOT NULL,
            PRIMARY KEY(livro_cod_l, autor_cod_au),
            CONSTRAINT FK_LIVRO_AUTOR_LIVRO FOREIGN KEY (livro_cod_l) REFERENCES livro (cod_l) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
            CONSTRAINT FK_LIVRO_AUTOR_AUTOR FOREIGN KEY (autor_cod_au) REFERENCES autor (cod_au) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE)');
        
        $this->addSql('CREATE INDEX IDX_67499921AE83779 ON livro_autor (autor_cod_au)');
        
        $this->addSql('CREATE TABLE livro_assunto (
            livro_cod_l INT NOT NULL,
            assunto_cod_as INT NOT NULL,
            PRIMARY KEY(livro_cod_l, assunto_cod_as),
            CONSTRAINT FK_LIVRO_ASSUNTO_LIVRO FOREIGN KEY (livro_cod_l) REFERENCES livro (cod_l) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
            CONSTRAINT FK_LIVRO_ASSUNTO_ASSUNTO FOREIGN KEY (assunto_cod_as) REFERENCES assunto (cod_as) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE)');

        $this->addSql('CREATE INDEX IDX_53C2C52A568DC9E5 ON livro_assunto (assunto_cod_as)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE livro_assunto');
        $this->addSql('DROP TABLE livro_autor');
        $this->addSql('DROP TABLE assunto');
        $this->addSql('DROP TABLE autor');
        $this->addSql('DROP TABLE livro');
    }
    
}
