<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260916231542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            name VARCHAR(45) NOT NULL, 
            last_name VARCHAR(45) NOT NULL,
            email VARCHAR(180) NOT NULL, 
            password VARCHAR(255) NOT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON users (email)');
        //TODO: Talvez implementar fila, mas acho que não será necessário
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE users');
    }
}
